"""Creator agent - generates LangGraph project blueprints from PROJECT_REQUEST."""

import json
from pathlib import Path
from typing import Dict, Any
from .schemas import ProjectRequest, GeneratedBlueprint
from .graph_template import get_graph_template, STATE_TEMPLATE


def load_creator_prompt() -> str:
    """Load the creator system prompt from file."""
    prompt_path = Path(__file__).parent.parent / "prompts" / "creator_system_prompt.txt"
    with open(prompt_path, 'r') as f:
        return f.read()


def build_blueprint(project_request: Dict[str, Any], use_llm: bool = False) -> Dict[str, Any]:
    """
    Generate a complete LangGraph project blueprint from PROJECT_REQUEST.
    
    Args:
        project_request: Validated PROJECT_REQUEST dict
        use_llm: If True, use LLM for generation (requires API)
                 If False, use template-based generation
    
    Returns:
        GeneratedBlueprint dict
    """
    if use_llm:
        raise NotImplementedError("LLM-based generation requires API setup")
    
    return _template_build(project_request)


def _template_build(project_request: Dict[str, Any]) -> Dict[str, Any]:
    """Template-based blueprint generation for offline use."""
    
    pr = ProjectRequest(**project_request)
    graph = get_graph_template()
    
    # Build file tree
    file_tree = [
        f"{pr.name}/",
        f"{pr.name}/README.md",
        f"{pr.name}/requirements.txt",
        f"{pr.name}/.env.example",
        f"{pr.name}/main.py",
        f"{pr.name}/graph.py",
        f"{pr.name}/state.py",
        f"{pr.name}/nodes/",
        f"{pr.name}/nodes/__init__.py",
        f"{pr.name}/nodes/ingest.py",
        f"{pr.name}/nodes/normalize.py",
        f"{pr.name}/nodes/validate.py",
        f"{pr.name}/adapters/",
        f"{pr.name}/adapters/__init__.py",
        f"{pr.name}/tests/",
        f"{pr.name}/tests/test_workflow.py",
        f"{pr.name}/examples/",
        f"{pr.name}/examples/test_payload.json"
    ]
    
    # Generate file contents (manifests, not full code)
    files = {
        "README.md": f"# {pr.name}\n\n{pr.goal}\n\nGenerated by LangChain Creator System.",
        "requirements.txt": "langchain\nlanggraph\nfastapi\nuvicorn\npydantic\n",
        ".env.example": "\n".join([f"{var}=your_value_here" for var in (pr.integrations or [])]),
        "state.py": STATE_TEMPLATE,
        "graph.py": "# LangGraph workflow implementation\n# Nodes: " + ", ".join([n['id'] for n in graph['nodes']])
    }
    
    # Build blueprint
    blueprint = GeneratedBlueprint(
        project_name=pr.name,
        workflow_graph=graph,
        state_schema=STATE_TEMPLATE,
        file_tree=file_tree,
        files=files,
        env_vars=pr.integrations or [],
        run_commands=[
            "pip install -r requirements.txt",
            "uvicorn main:app --reload"
        ],
        tests=["pytest tests/"],
        limitations=["Template-based generation; review and customize before production use"]
    )
    
    return blueprint.model_dump()
